##Configurations for training the quntum kernel alignment 

ray_config:
  ray_local_mode:         False
  num_cpus:               20
  num_gpus:               2
  method:                 QuantumKernels
  ray_logging_path:       logs/checkerboard
  ray_num_trial_samples:  5
  type:                   train

## DataSet Configuration
dataset:
  name:              mnist_fashion
  file:              None
  n_samples:         200
  training_size:     0.60
  testing_size:      0.40
  validation_size:   0.0
  pca_features:      5

## Quantum Kernel Model Configuration
qnn:
  device:           lightning.qubit
  n_qubits:         5
  input_scaling:    True
  data_reuploading: True
  ansatz:           'he'
  ansatz_layers:    5

## Model Training Agent Configuration
agent:
  optimizer:            adam
  lr:                   [0.2, 0.1, 0.01]
  epochs:               20
  train_method:         ccka
  target_accuracy:      0.95
  get_alignment_every:  5
  validate_every_epoch: 10
  base_path:            results/

